input {
  file {
    path => "/usr/share/logstash/data/uploads/*.csv"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    tags => ["csv_import"]
  }
}

filter {
  if "csv_import" in [tags] {
    csv {
      separator => ","
      columns => ["timestamp", "level", "service", "user_id", "action", "message", "ip_address", "response_time_ms"]
      skip_header => "true"
    }
    
    date {
      match => ["timestamp", "ISO8601", "yyyy-MM-dd HH:mm:ss"]
      target => "@timestamp"
    }
  }
}

output {
  if "csv_import" in [tags] {
    elasticsearch {
      hosts => ["elasticsearch:9200"]
      index => "logs_csv-%{+YYYY.MM.dd}"
    }
    stdout { codec => rubydebug }
  }
}
